# This file automatically generated by vpl
# please do not modify => safely modified by dopark
# set vpp_link_root "./"
# set vpl_root "$vpp_link_root/vivado/vpl"
# set local_dir "$vpl_root/.local"

set vivado_error_file "vivado_error.txt"
set vivado_warn_file "vivado_warning.txt"
set vivado_output_dir "./output"
set output_dir "./output"
set vpl_output_dir "./int"
set input_dir "./input"
set steps_log "./link.steps.log"
