// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="data_redir_m_data_redir_m,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.593125,HLS_SYN_LAT=9,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=363,HLS_SYN_LUT=1818,HLS_VERSION=2022_1}" *)

module data_redir_m (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_TDATA,
        Input_1_TVALID,
        Input_1_TREADY,
        Output_1_TDATA,
        Output_1_TVALID,
        Output_1_TREADY,
        Output_2_TDATA,
        Output_2_TVALID,
        Output_2_TREADY
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] Input_1_TDATA;
input   Input_1_TVALID;
output   Input_1_TREADY;
output  [31:0] Output_1_TDATA;
output   Output_1_TVALID;
input   Output_1_TREADY;
output  [31:0] Output_2_TDATA;
output   Output_2_TVALID;
input   Output_2_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Input_1_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg   [7:0] triangle_2ds_1_x0_V_reg_232;
reg   [7:0] triangle_2ds_1_y0_V_reg_237;
reg   [7:0] triangle_2ds_1_x1_V_reg_242;
reg   [7:0] triangle_2ds_1_y1_V_reg_247;
reg   [7:0] triangle_2ds_1_x2_V_reg_252;
reg   [7:0] triangle_2ds_1_y2_V_reg_257;
reg   [7:0] triangle_2ds_1_z_V_reg_262;
reg   [7:0] triangle_2ds_2_x0_V_reg_267;
reg   [7:0] triangle_2ds_2_y0_V_reg_272;
reg   [7:0] triangle_2ds_2_x1_V_reg_277;
reg   [7:0] triangle_2ds_2_y1_V_reg_282;
reg   [7:0] triangle_2ds_2_x2_V_reg_287;
reg   [7:0] triangle_2ds_2_y2_V_reg_292;
reg   [7:0] triangle_2ds_2_z_V_reg_297;
wire    call_ret_projection_odd_m_fu_78_ap_ready;
wire   [31:0] call_ret_projection_odd_m_fu_78_input_lo;
wire   [31:0] call_ret_projection_odd_m_fu_78_input_mi;
wire   [7:0] call_ret_projection_odd_m_fu_78_input_hi;
wire   [7:0] call_ret_projection_odd_m_fu_78_ap_return_0;
wire   [7:0] call_ret_projection_odd_m_fu_78_ap_return_1;
wire   [7:0] call_ret_projection_odd_m_fu_78_ap_return_2;
wire   [7:0] call_ret_projection_odd_m_fu_78_ap_return_3;
wire   [7:0] call_ret_projection_odd_m_fu_78_ap_return_4;
wire   [7:0] call_ret_projection_odd_m_fu_78_ap_return_5;
wire   [7:0] call_ret_projection_odd_m_fu_78_ap_return_6;
wire    call_ret1_projection_even_m_fu_85_ap_ready;
wire   [31:0] call_ret1_projection_even_m_fu_85_input_lo;
wire   [31:0] call_ret1_projection_even_m_fu_85_input_mi;
wire   [7:0] call_ret1_projection_even_m_fu_85_input_hi;
wire   [7:0] call_ret1_projection_even_m_fu_85_ap_return_0;
wire   [7:0] call_ret1_projection_even_m_fu_85_ap_return_1;
wire   [7:0] call_ret1_projection_even_m_fu_85_ap_return_2;
wire   [7:0] call_ret1_projection_even_m_fu_85_ap_return_3;
wire   [7:0] call_ret1_projection_even_m_fu_85_ap_return_4;
wire   [7:0] call_ret1_projection_even_m_fu_85_ap_return_5;
wire   [7:0] call_ret1_projection_even_m_fu_85_ap_return_6;
wire    grp_rasterization1_odd_m_fu_92_ap_start;
wire    grp_rasterization1_odd_m_fu_92_ap_done;
wire    grp_rasterization1_odd_m_fu_92_ap_idle;
wire    grp_rasterization1_odd_m_fu_92_ap_ready;
wire   [31:0] grp_rasterization1_odd_m_fu_92_Output_1_TDATA;
wire    grp_rasterization1_odd_m_fu_92_Output_1_TVALID;
wire    grp_rasterization1_odd_m_fu_92_Output_1_TREADY;
wire    grp_rasterization1_even_m_fu_117_ap_start;
wire    grp_rasterization1_even_m_fu_117_ap_done;
wire    grp_rasterization1_even_m_fu_117_ap_idle;
wire    grp_rasterization1_even_m_fu_117_ap_ready;
wire   [31:0] grp_rasterization1_even_m_fu_117_Output_2_TDATA;
wire    grp_rasterization1_even_m_fu_117_Output_2_TVALID;
wire    grp_rasterization1_even_m_fu_117_Output_2_TREADY;
reg    grp_rasterization1_odd_m_fu_92_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_block_state4_on_subcall_done;
reg    grp_rasterization1_even_m_fu_117_ap_start_reg;
reg    ap_block_state1;
wire    ap_CS_fsm_state5;
wire    regslice_both_Output_1_U_apdone_blk;
wire    regslice_both_Output_2_U_apdone_blk;
reg    ap_block_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_Input_1_U_apdone_blk;
wire   [127:0] Input_1_TDATA_int_regslice;
wire    Input_1_TVALID_int_regslice;
reg    Input_1_TREADY_int_regslice;
wire    regslice_both_Input_1_U_ack_in;
wire    Output_1_TREADY_int_regslice;
wire    regslice_both_Output_1_U_vld_out;
wire    Output_2_TREADY_int_regslice;
wire    regslice_both_Output_2_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_rasterization1_odd_m_fu_92_ap_start_reg = 1'b0;
#0 grp_rasterization1_even_m_fu_117_ap_start_reg = 1'b0;
end

data_redir_m_projection_odd_m call_ret_projection_odd_m_fu_78(
    .ap_ready(call_ret_projection_odd_m_fu_78_ap_ready),
    .input_lo(call_ret_projection_odd_m_fu_78_input_lo),
    .input_mi(call_ret_projection_odd_m_fu_78_input_mi),
    .input_hi(call_ret_projection_odd_m_fu_78_input_hi),
    .ap_return_0(call_ret_projection_odd_m_fu_78_ap_return_0),
    .ap_return_1(call_ret_projection_odd_m_fu_78_ap_return_1),
    .ap_return_2(call_ret_projection_odd_m_fu_78_ap_return_2),
    .ap_return_3(call_ret_projection_odd_m_fu_78_ap_return_3),
    .ap_return_4(call_ret_projection_odd_m_fu_78_ap_return_4),
    .ap_return_5(call_ret_projection_odd_m_fu_78_ap_return_5),
    .ap_return_6(call_ret_projection_odd_m_fu_78_ap_return_6)
);

data_redir_m_projection_even_m call_ret1_projection_even_m_fu_85(
    .ap_ready(call_ret1_projection_even_m_fu_85_ap_ready),
    .input_lo(call_ret1_projection_even_m_fu_85_input_lo),
    .input_mi(call_ret1_projection_even_m_fu_85_input_mi),
    .input_hi(call_ret1_projection_even_m_fu_85_input_hi),
    .ap_return_0(call_ret1_projection_even_m_fu_85_ap_return_0),
    .ap_return_1(call_ret1_projection_even_m_fu_85_ap_return_1),
    .ap_return_2(call_ret1_projection_even_m_fu_85_ap_return_2),
    .ap_return_3(call_ret1_projection_even_m_fu_85_ap_return_3),
    .ap_return_4(call_ret1_projection_even_m_fu_85_ap_return_4),
    .ap_return_5(call_ret1_projection_even_m_fu_85_ap_return_5),
    .ap_return_6(call_ret1_projection_even_m_fu_85_ap_return_6)
);

data_redir_m_rasterization1_odd_m grp_rasterization1_odd_m_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_rasterization1_odd_m_fu_92_ap_start),
    .ap_done(grp_rasterization1_odd_m_fu_92_ap_done),
    .ap_idle(grp_rasterization1_odd_m_fu_92_ap_idle),
    .ap_ready(grp_rasterization1_odd_m_fu_92_ap_ready),
    .triangle_2d_x0(triangle_2ds_1_x0_V_reg_232),
    .triangle_2d_y0(triangle_2ds_1_y0_V_reg_237),
    .triangle_2d_x1(triangle_2ds_1_x1_V_reg_242),
    .triangle_2d_y1(triangle_2ds_1_y1_V_reg_247),
    .triangle_2d_x2(triangle_2ds_1_x2_V_reg_252),
    .triangle_2d_y2(triangle_2ds_1_y2_V_reg_257),
    .triangle_2d_z(triangle_2ds_1_z_V_reg_262),
    .Output_1_TDATA(grp_rasterization1_odd_m_fu_92_Output_1_TDATA),
    .Output_1_TVALID(grp_rasterization1_odd_m_fu_92_Output_1_TVALID),
    .Output_1_TREADY(grp_rasterization1_odd_m_fu_92_Output_1_TREADY)
);

data_redir_m_rasterization1_even_m grp_rasterization1_even_m_fu_117(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_rasterization1_even_m_fu_117_ap_start),
    .ap_done(grp_rasterization1_even_m_fu_117_ap_done),
    .ap_idle(grp_rasterization1_even_m_fu_117_ap_idle),
    .ap_ready(grp_rasterization1_even_m_fu_117_ap_ready),
    .triangle_2d_x0(triangle_2ds_2_x0_V_reg_267),
    .triangle_2d_y0(triangle_2ds_2_y0_V_reg_272),
    .triangle_2d_x1(triangle_2ds_2_x1_V_reg_277),
    .triangle_2d_y1(triangle_2ds_2_y1_V_reg_282),
    .triangle_2d_x2(triangle_2ds_2_x2_V_reg_287),
    .triangle_2d_y2(triangle_2ds_2_y2_V_reg_292),
    .triangle_2d_z(triangle_2ds_2_z_V_reg_297),
    .Output_2_TDATA(grp_rasterization1_even_m_fu_117_Output_2_TDATA),
    .Output_2_TVALID(grp_rasterization1_even_m_fu_117_Output_2_TVALID),
    .Output_2_TREADY(grp_rasterization1_even_m_fu_117_Output_2_TREADY)
);

data_redir_m_regslice_both #(
    .DataWidth( 128 ))
regslice_both_Input_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_1_TDATA),
    .vld_in(Input_1_TVALID),
    .ack_in(regslice_both_Input_1_U_ack_in),
    .data_out(Input_1_TDATA_int_regslice),
    .vld_out(Input_1_TVALID_int_regslice),
    .ack_out(Input_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_1_U_apdone_blk)
);

data_redir_m_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Output_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_rasterization1_odd_m_fu_92_Output_1_TDATA),
    .vld_in(grp_rasterization1_odd_m_fu_92_Output_1_TVALID),
    .ack_in(Output_1_TREADY_int_regslice),
    .data_out(Output_1_TDATA),
    .vld_out(regslice_both_Output_1_U_vld_out),
    .ack_out(Output_1_TREADY),
    .apdone_blk(regslice_both_Output_1_U_apdone_blk)
);

data_redir_m_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Output_2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_rasterization1_even_m_fu_117_Output_2_TDATA),
    .vld_in(grp_rasterization1_even_m_fu_117_Output_2_TVALID),
    .ack_in(Output_2_TREADY_int_regslice),
    .data_out(Output_2_TDATA),
    .vld_out(regslice_both_Output_2_U_vld_out),
    .ack_out(Output_2_TREADY),
    .apdone_blk(regslice_both_Output_2_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_rasterization1_even_m_fu_117_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_rasterization1_even_m_fu_117_ap_start_reg <= 1'b1;
        end else if ((grp_rasterization1_even_m_fu_117_ap_ready == 1'b1)) begin
            grp_rasterization1_even_m_fu_117_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_rasterization1_odd_m_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_rasterization1_odd_m_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_rasterization1_odd_m_fu_92_ap_ready == 1'b1)) begin
            grp_rasterization1_odd_m_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        triangle_2ds_1_x0_V_reg_232 <= call_ret_projection_odd_m_fu_78_ap_return_0;
        triangle_2ds_1_x1_V_reg_242 <= call_ret_projection_odd_m_fu_78_ap_return_2;
        triangle_2ds_1_x2_V_reg_252 <= call_ret_projection_odd_m_fu_78_ap_return_4;
        triangle_2ds_1_y0_V_reg_237 <= call_ret_projection_odd_m_fu_78_ap_return_1;
        triangle_2ds_1_y1_V_reg_247 <= call_ret_projection_odd_m_fu_78_ap_return_3;
        triangle_2ds_1_y2_V_reg_257 <= call_ret_projection_odd_m_fu_78_ap_return_5;
        triangle_2ds_1_z_V_reg_262 <= call_ret_projection_odd_m_fu_78_ap_return_6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        triangle_2ds_2_x0_V_reg_267 <= call_ret1_projection_even_m_fu_85_ap_return_0;
        triangle_2ds_2_x1_V_reg_277 <= call_ret1_projection_even_m_fu_85_ap_return_2;
        triangle_2ds_2_x2_V_reg_287 <= call_ret1_projection_even_m_fu_85_ap_return_4;
        triangle_2ds_2_y0_V_reg_272 <= call_ret1_projection_even_m_fu_85_ap_return_1;
        triangle_2ds_2_y1_V_reg_282 <= call_ret1_projection_even_m_fu_85_ap_return_3;
        triangle_2ds_2_y2_V_reg_292 <= call_ret1_projection_even_m_fu_85_ap_return_5;
        triangle_2ds_2_z_V_reg_297 <= call_ret1_projection_even_m_fu_85_ap_return_6;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        Input_1_TDATA_blk_n = Input_1_TVALID_int_regslice;
    end else begin
        Input_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'b1 == Input_1_TVALID_int_regslice)) | (~((1'b0 == Input_1_TVALID_int_regslice) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        Input_1_TREADY_int_regslice = 1'b1;
    end else begin
        Input_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == Input_1_TVALID_int_regslice) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == Input_1_TVALID_int_regslice)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_Output_2_U_apdone_blk == 1'b1) | (regslice_both_Output_1_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_Output_2_U_apdone_blk == 1'b1) | (regslice_both_Output_1_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_Output_2_U_apdone_blk == 1'b1) | (regslice_both_Output_1_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == Input_1_TVALID_int_regslice) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b1 == Input_1_TVALID_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((regslice_both_Output_2_U_apdone_blk == 1'b1) | (regslice_both_Output_1_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Input_1_TREADY = regslice_both_Input_1_U_ack_in;

assign Output_1_TVALID = regslice_both_Output_1_U_vld_out;

assign Output_2_TVALID = regslice_both_Output_2_U_vld_out;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((1'b0 == Input_1_TVALID_int_regslice) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_rasterization1_even_m_fu_117_ap_done == 1'b0) | (grp_rasterization1_odd_m_fu_92_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((regslice_both_Output_2_U_apdone_blk == 1'b1) | (regslice_both_Output_1_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign call_ret1_projection_even_m_fu_85_input_hi = {{Input_1_TDATA_int_regslice[71:64]}};

assign call_ret1_projection_even_m_fu_85_input_lo = Input_1_TDATA_int_regslice[31:0];

assign call_ret1_projection_even_m_fu_85_input_mi = {{Input_1_TDATA_int_regslice[63:32]}};

assign call_ret_projection_odd_m_fu_78_input_hi = {{Input_1_TDATA_int_regslice[71:64]}};

assign call_ret_projection_odd_m_fu_78_input_lo = Input_1_TDATA_int_regslice[31:0];

assign call_ret_projection_odd_m_fu_78_input_mi = {{Input_1_TDATA_int_regslice[63:32]}};

assign grp_rasterization1_even_m_fu_117_Output_2_TREADY = (ap_CS_fsm_state4 & Output_2_TREADY_int_regslice);

assign grp_rasterization1_even_m_fu_117_ap_start = grp_rasterization1_even_m_fu_117_ap_start_reg;

assign grp_rasterization1_odd_m_fu_92_Output_1_TREADY = (ap_CS_fsm_state4 & Output_1_TREADY_int_regslice);

assign grp_rasterization1_odd_m_fu_92_ap_start = grp_rasterization1_odd_m_fu_92_ap_start_reg;

endmodule //data_redir_m
