// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="zculling_bot_zculling_bot,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.323000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=19,HLS_SYN_DSP=0,HLS_SYN_FF=295,HLS_SYN_LUT=6609,HLS_VERSION=2022_1}" *)

module zculling_bot (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_TDATA,
        Input_1_TVALID,
        Input_1_TREADY,
        Input_2_TDATA,
        Input_2_TVALID,
        Input_2_TREADY,
        Output_1_TDATA,
        Output_1_TVALID,
        Output_1_TREADY
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] Input_1_TDATA;
input   Input_1_TVALID;
output   Input_1_TREADY;
input  [31:0] Input_2_TDATA;
input   Input_2_TVALID;
output   Input_2_TREADY;
output  [31:0] Output_1_TDATA;
output   Output_1_TVALID;
input   Output_1_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] odd_even_V;
reg   [15:0] counter_V;
reg   [14:0] z_buffer_V_address0;
reg    z_buffer_V_ce0;
reg    z_buffer_V_we0;
reg   [7:0] z_buffer_V_d0;
wire   [7:0] z_buffer_V_q0;
reg    z_buffer_V_ce1;
reg    z_buffer_V_we1;
reg    Input_1_TDATA_blk_n;
reg    Input_2_TDATA_blk_n;
reg    Output_1_TDATA_blk_n;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [0:0] odd_even_V_load_reg_200;
wire   [15:0] trunc_ln155_fu_136_p1;
reg   [15:0] trunc_ln155_reg_205;
wire   [0:0] icmp_ln1065_fu_144_p2;
reg   [0:0] icmp_ln1065_reg_213;
wire   [31:0] zext_ln232_fu_189_p1;
reg   [8:0] pixels_x_V_address0;
reg    pixels_x_V_ce0;
reg    pixels_x_V_we0;
wire   [7:0] pixels_x_V_q0;
reg   [8:0] pixels_y_V_address0;
reg    pixels_y_V_ce0;
reg    pixels_y_V_we0;
wire   [7:0] pixels_y_V_q0;
reg   [8:0] pixels_color_V_address0;
reg    pixels_color_V_ce0;
reg    pixels_color_V_we0;
wire   [7:0] pixels_color_V_q0;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_done;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_idle;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_ready;
wire   [14:0] grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_address0;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_ce0;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_we0;
wire   [7:0] grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_d0;
wire   [14:0] grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_address1;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_ce1;
wire    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_we1;
wire   [7:0] grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_d1;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_done;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_idle;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_ready;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_Input_1_TREADY;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_Input_2_TREADY;
wire   [8:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_address0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_ce0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_we0;
wire   [7:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_d0;
wire   [8:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_address0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_ce0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_we0;
wire   [7:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_d0;
wire   [8:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_address0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_ce0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_we0;
wire   [7:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_d0;
wire   [15:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixel_cntr_V_out;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixel_cntr_V_out_ap_vld;
wire   [14:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_address0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_ce0;
wire    grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_we0;
wire   [7:0] grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_d0;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_done;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_idle;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_ready;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TREADY;
wire   [8:0] grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_x_V_address0;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_x_V_ce0;
wire   [8:0] grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_y_V_address0;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_y_V_ce0;
wire   [8:0] grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_color_V_address0;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_color_V_ce0;
wire   [31:0] grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TDATA;
wire    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TVALID;
reg   [31:0] ap_phi_mux_size_0_in_in_in_phi_fu_92_p4;
reg    ap_block_state1;
reg    grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start_reg;
reg    ap_block_state1_ignore_call0;
wire    ap_CS_fsm_state2;
reg    grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [0:0] r_V_fu_155_p2;
reg    ap_block_state2_on_subcall_done;
wire   [15:0] select_ln107_fu_172_p3;
wire   [15:0] add_ln886_fu_150_p2;
wire   [0:0] icmp_ln1065_1_fu_166_p2;
wire    ap_CS_fsm_state9;
wire    regslice_both_Output_1_U_apdone_blk;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    regslice_both_Input_1_U_apdone_blk;
wire   [31:0] Input_1_TDATA_int_regslice;
wire    Input_1_TVALID_int_regslice;
reg    Input_1_TREADY_int_regslice;
wire    regslice_both_Input_1_U_ack_in;
wire    regslice_both_Input_2_U_apdone_blk;
wire   [31:0] Input_2_TDATA_int_regslice;
wire    Input_2_TVALID_int_regslice;
reg    Input_2_TREADY_int_regslice;
wire    regslice_both_Input_2_U_ack_in;
reg   [31:0] Output_1_TDATA_int_regslice;
reg    Output_1_TVALID_int_regslice;
wire    Output_1_TREADY_int_regslice;
wire    regslice_both_Output_1_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 odd_even_V = 1'd0;
#0 counter_V = 16'd0;
#0 grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start_reg = 1'b0;
#0 grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start_reg = 1'b0;
#0 grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start_reg = 1'b0;
end

zculling_bot_z_buffer_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 32768 ),
    .AddressWidth( 15 ))
z_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(z_buffer_V_address0),
    .ce0(z_buffer_V_ce0),
    .we0(z_buffer_V_we0),
    .d0(z_buffer_V_d0),
    .q0(z_buffer_V_q0),
    .address1(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_address1),
    .ce1(z_buffer_V_ce1),
    .we1(z_buffer_V_we1),
    .d1(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_d1)
);

zculling_bot_pixels_x_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
pixels_x_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pixels_x_V_address0),
    .ce0(pixels_x_V_ce0),
    .we0(pixels_x_V_we0),
    .d0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_d0),
    .q0(pixels_x_V_q0)
);

zculling_bot_pixels_x_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
pixels_y_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pixels_y_V_address0),
    .ce0(pixels_y_V_ce0),
    .we0(pixels_y_V_we0),
    .d0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_d0),
    .q0(pixels_y_V_q0)
);

zculling_bot_pixels_x_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
pixels_color_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pixels_color_V_address0),
    .ce0(pixels_color_V_ce0),
    .we0(pixels_color_V_we0),
    .d0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_d0),
    .q0(pixels_color_V_q0)
);

zculling_bot_zculling_bot_Pipeline_ZCULLING_INIT_ROW grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start),
    .ap_done(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_done),
    .ap_idle(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_idle),
    .ap_ready(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_ready),
    .z_buffer_V_address0(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_address0),
    .z_buffer_V_ce0(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_ce0),
    .z_buffer_V_we0(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_we0),
    .z_buffer_V_d0(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_d0),
    .z_buffer_V_address1(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_address1),
    .z_buffer_V_ce1(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_ce1),
    .z_buffer_V_we1(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_we1),
    .z_buffer_V_d1(grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_d1)
);

zculling_bot_zculling_bot_Pipeline_ZCULLING grp_zculling_bot_Pipeline_ZCULLING_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start),
    .ap_done(grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_done),
    .ap_idle(grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_idle),
    .ap_ready(grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_ready),
    .Input_1_TVALID(Input_1_TVALID_int_regslice),
    .Input_2_TVALID(Input_2_TVALID_int_regslice),
    .trunc_ln(trunc_ln155_reg_205),
    .Input_1_TDATA(Input_1_TDATA_int_regslice),
    .Input_1_TREADY(grp_zculling_bot_Pipeline_ZCULLING_fu_106_Input_1_TREADY),
    .odd_even_V_load(odd_even_V_load_reg_200),
    .Input_2_TDATA(Input_2_TDATA_int_regslice),
    .Input_2_TREADY(grp_zculling_bot_Pipeline_ZCULLING_fu_106_Input_2_TREADY),
    .pixels_x_V_address0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_address0),
    .pixels_x_V_ce0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_ce0),
    .pixels_x_V_we0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_we0),
    .pixels_x_V_d0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_d0),
    .pixels_y_V_address0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_address0),
    .pixels_y_V_ce0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_ce0),
    .pixels_y_V_we0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_we0),
    .pixels_y_V_d0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_d0),
    .pixels_color_V_address0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_address0),
    .pixels_color_V_ce0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_ce0),
    .pixels_color_V_we0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_we0),
    .pixels_color_V_d0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_d0),
    .pixel_cntr_V_out(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixel_cntr_V_out),
    .pixel_cntr_V_out_ap_vld(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixel_cntr_V_out_ap_vld),
    .z_buffer_V_address0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_address0),
    .z_buffer_V_ce0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_ce0),
    .z_buffer_V_we0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_we0),
    .z_buffer_V_d0(grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_d0),
    .z_buffer_V_q0(z_buffer_V_q0)
);

zculling_bot_zculling_bot_Pipeline_VITIS_LOOP_92_1 grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start),
    .ap_done(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_done),
    .ap_idle(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_idle),
    .ap_ready(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_ready),
    .Output_1_TREADY(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TREADY),
    .pixel_cntr_V_reload(grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixel_cntr_V_out),
    .pixels_x_V_address0(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_x_V_address0),
    .pixels_x_V_ce0(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_x_V_ce0),
    .pixels_x_V_q0(pixels_x_V_q0),
    .pixels_y_V_address0(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_y_V_address0),
    .pixels_y_V_ce0(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_y_V_ce0),
    .pixels_y_V_q0(pixels_y_V_q0),
    .pixels_color_V_address0(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_color_V_address0),
    .pixels_color_V_ce0(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_color_V_ce0),
    .pixels_color_V_q0(pixels_color_V_q0),
    .Output_1_TDATA(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TDATA),
    .Output_1_TVALID(grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TVALID)
);

zculling_bot_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Input_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_1_TDATA),
    .vld_in(Input_1_TVALID),
    .ack_in(regslice_both_Input_1_U_ack_in),
    .data_out(Input_1_TDATA_int_regslice),
    .vld_out(Input_1_TVALID_int_regslice),
    .ack_out(Input_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_1_U_apdone_blk)
);

zculling_bot_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Input_2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Input_2_TDATA),
    .vld_in(Input_2_TVALID),
    .ack_in(regslice_both_Input_2_U_ack_in),
    .data_out(Input_2_TDATA_int_regslice),
    .vld_out(Input_2_TVALID_int_regslice),
    .ack_out(Input_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_Input_2_U_apdone_blk)
);

zculling_bot_regslice_both #(
    .DataWidth( 32 ))
regslice_both_Output_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(Output_1_TDATA_int_regslice),
    .vld_in(Output_1_TVALID_int_regslice),
    .ack_in(Output_1_TREADY_int_regslice),
    .data_out(Output_1_TDATA),
    .vld_out(regslice_both_Output_1_U_vld_out),
    .ack_out(Output_1_TREADY),
    .apdone_blk(regslice_both_Output_1_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_ready == 1'b1)) begin
            grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | ((odd_even_V == 1'd1) & (1'b0 == Input_2_TVALID_int_regslice)) | ((odd_even_V == 1'd0) & (1'b0 == Input_1_TVALID_int_regslice))) & (icmp_ln1065_fu_144_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_ready == 1'b1)) begin
            grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_ready == 1'b1)) begin
            grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        counter_V <= select_ln107_fu_172_p3;
        odd_even_V <= r_V_fu_155_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1065_reg_213 <= icmp_ln1065_fu_144_p2;
        odd_even_V_load_reg_200 <= odd_even_V;
        trunc_ln155_reg_205 <= trunc_ln155_fu_136_p1;
    end
end

always @ (*) begin
    if (((odd_even_V == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        Input_1_TDATA_blk_n = Input_1_TVALID_int_regslice;
    end else begin
        Input_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | ((odd_even_V == 1'd1) & (1'b0 == Input_2_TVALID_int_regslice)) | ((odd_even_V == 1'd0) & (1'b0 == Input_1_TVALID_int_regslice))) & (odd_even_V == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        Input_1_TREADY_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Input_1_TREADY_int_regslice = grp_zculling_bot_Pipeline_ZCULLING_fu_106_Input_1_TREADY;
    end else begin
        Input_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((odd_even_V == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        Input_2_TDATA_blk_n = Input_2_TVALID_int_regslice;
    end else begin
        Input_2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | ((odd_even_V == 1'd1) & (1'b0 == Input_2_TVALID_int_regslice)) | ((odd_even_V == 1'd0) & (1'b0 == Input_1_TVALID_int_regslice))) & (odd_even_V == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        Input_2_TREADY_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Input_2_TREADY_int_regslice = grp_zculling_bot_Pipeline_ZCULLING_fu_106_Input_2_TREADY;
    end else begin
        Input_2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        Output_1_TDATA_blk_n = Output_1_TREADY_int_regslice;
    end else begin
        Output_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == Output_1_TREADY_int_regslice))) begin
        Output_1_TDATA_int_regslice = zext_ln232_fu_189_p1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TVALID == 1'b1))) begin
        Output_1_TDATA_int_regslice = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TDATA;
    end else begin
        Output_1_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == Output_1_TREADY_int_regslice))) begin
        Output_1_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        Output_1_TVALID_int_regslice = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TVALID;
    end else begin
        Output_1_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | ((odd_even_V == 1'd1) & (1'b0 == Input_2_TVALID_int_regslice)) | ((odd_even_V == 1'd0) & (1'b0 == Input_1_TVALID_int_regslice)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == Output_1_TREADY_int_regslice)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == Output_1_TREADY_int_regslice)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_Output_1_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_Output_1_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((odd_even_V == 1'd1)) begin
            ap_phi_mux_size_0_in_in_in_phi_fu_92_p4 = Input_2_TDATA_int_regslice;
        end else if ((odd_even_V == 1'd0)) begin
            ap_phi_mux_size_0_in_in_in_phi_fu_92_p4 = Input_1_TDATA_int_regslice;
        end else begin
            ap_phi_mux_size_0_in_in_in_phi_fu_92_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_size_0_in_in_in_phi_fu_92_p4 = 'bx;
    end
end

always @ (*) begin
    if (((regslice_both_Output_1_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pixels_color_V_address0 = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_color_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_color_V_address0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_address0;
    end else begin
        pixels_color_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pixels_color_V_ce0 = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_color_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_color_V_ce0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_ce0;
    end else begin
        pixels_color_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_color_V_we0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_color_V_we0;
    end else begin
        pixels_color_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pixels_x_V_address0 = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_x_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_x_V_address0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_address0;
    end else begin
        pixels_x_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pixels_x_V_ce0 = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_x_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_x_V_ce0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_ce0;
    end else begin
        pixels_x_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_x_V_we0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_x_V_we0;
    end else begin
        pixels_x_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pixels_y_V_address0 = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_y_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_y_V_address0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_address0;
    end else begin
        pixels_y_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pixels_y_V_ce0 = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_pixels_y_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_y_V_ce0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_ce0;
    end else begin
        pixels_y_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixels_y_V_we0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixels_y_V_we0;
    end else begin
        pixels_y_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        z_buffer_V_address0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_address0;
    end else if (((icmp_ln1065_reg_213 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        z_buffer_V_address0 = grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_address0;
    end else begin
        z_buffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        z_buffer_V_ce0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_ce0;
    end else if (((icmp_ln1065_reg_213 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        z_buffer_V_ce0 = grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_ce0;
    end else begin
        z_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1065_reg_213 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        z_buffer_V_ce1 = grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_ce1;
    end else begin
        z_buffer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        z_buffer_V_d0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_d0;
    end else if (((icmp_ln1065_reg_213 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        z_buffer_V_d0 = grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_d0;
    end else begin
        z_buffer_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        z_buffer_V_we0 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_z_buffer_V_we0;
    end else if (((icmp_ln1065_reg_213 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        z_buffer_V_we0 = grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_we0;
    end else begin
        z_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1065_reg_213 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        z_buffer_V_we1 = grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_z_buffer_V_we1;
    end else begin
        z_buffer_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | ((odd_even_V == 1'd1) & (1'b0 == Input_2_TVALID_int_regslice)) | ((odd_even_V == 1'd0) & (1'b0 == Input_1_TVALID_int_regslice))) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == Output_1_TREADY_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b1 == Output_1_TREADY_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((regslice_both_Output_1_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Input_1_TREADY = regslice_both_Input_1_U_ack_in;

assign Input_2_TREADY = regslice_both_Input_2_U_ack_in;

assign Output_1_TVALID = regslice_both_Output_1_U_vld_out;

assign add_ln886_fu_150_p2 = (counter_V + 16'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((odd_even_V == 1'd1) & (1'b0 == Input_2_TVALID_int_regslice)) | ((odd_even_V == 1'd0) & (1'b0 == Input_1_TVALID_int_regslice)));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_start == 1'b0) | ((odd_even_V == 1'd1) & (1'b0 == Input_2_TVALID_int_regslice)) | ((odd_even_V == 1'd0) & (1'b0 == Input_1_TVALID_int_regslice)));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((icmp_ln1065_reg_213 == 1'd1) & (grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_Output_1_TREADY = (ap_CS_fsm_state8 & Output_1_TREADY_int_regslice);

assign grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start = grp_zculling_bot_Pipeline_VITIS_LOOP_92_1_fu_122_ap_start_reg;

assign grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start = grp_zculling_bot_Pipeline_ZCULLING_INIT_ROW_fu_100_ap_start_reg;

assign grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start = grp_zculling_bot_Pipeline_ZCULLING_fu_106_ap_start_reg;

assign icmp_ln1065_1_fu_166_p2 = ((add_ln886_fu_150_p2 == 16'd3192) ? 1'b1 : 1'b0);

assign icmp_ln1065_fu_144_p2 = ((counter_V == 16'd0) ? 1'b1 : 1'b0);

assign r_V_fu_155_p2 = (odd_even_V ^ 1'd1);

assign select_ln107_fu_172_p3 = ((icmp_ln1065_1_fu_166_p2[0:0] == 1'b1) ? 16'd0 : add_ln886_fu_150_p2);

assign trunc_ln155_fu_136_p1 = ap_phi_mux_size_0_in_in_in_phi_fu_92_p4[15:0];

assign zext_ln232_fu_189_p1 = grp_zculling_bot_Pipeline_ZCULLING_fu_106_pixel_cntr_V_out;

endmodule //zculling_bot
