// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="config_parser_config_parser,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.219000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=799,HLS_SYN_LUT=2945,HLS_VERSION=2022_1}" *)

module config_parser (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input1_TDATA,
        input1_TVALID,
        input1_TREADY,
        input2_TDATA,
        input2_TVALID,
        input2_TREADY,
        input3_TDATA,
        input3_TVALID,
        input3_TREADY,
        output1_TDATA,
        output1_TVALID,
        output1_TREADY,
        output2_TDATA,
        output2_TVALID,
        output2_TREADY,
        output3_TDATA,
        output3_TVALID,
        output3_TREADY,
        output4_TDATA,
        output4_TVALID,
        output4_TREADY
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] input1_TDATA;
input   input1_TVALID;
output   input1_TREADY;
input  [511:0] input2_TDATA;
input   input2_TVALID;
output   input2_TREADY;
input  [7:0] input3_TDATA;
input   input3_TVALID;
output   input3_TREADY;
output  [63:0] output1_TDATA;
output   output1_TVALID;
input   output1_TREADY;
output  [31:0] output2_TDATA;
output   output2_TVALID;
input   output2_TREADY;
output  [31:0] output3_TDATA;
output   output3_TVALID;
input   output3_TREADY;
output  [15:0] output4_TDATA;
output   output4_TVALID;
input   output4_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    input1_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    input2_TDATA_blk_n;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln51_fu_174_p2;
reg    input3_TDATA_blk_n;
wire    ap_CS_fsm_state17;
reg    output3_TDATA_blk_n;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    output4_TDATA_blk_n;
wire   [31:0] config_num_fu_141_p1;
reg   [31:0] config_num_reg_194;
wire   [31:0] data_num_fu_145_p1;
reg   [31:0] data_num_reg_201;
wire   [31:0] num_ops_fu_149_p1;
reg   [31:0] num_ops_reg_206;
wire   [31:0] output_size_fu_153_p1;
reg   [31:0] output_size_reg_212;
wire   [15:0] trunc_ln232_fu_157_p1;
reg   [15:0] trunc_ln232_reg_217;
wire   [0:0] icmp_ln35_fu_161_p2;
reg   [511:0] tmp_1_reg_236;
reg   [7:0] v1_buffer_V_address0;
reg    v1_buffer_V_ce0;
reg    v1_buffer_V_we0;
reg   [63:0] v1_buffer_V_d0;
wire   [63:0] v1_buffer_V_q0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_input1_TREADY;
wire   [7:0] grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_address0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_ce0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_we0;
wire   [63:0] grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_d0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TREADY;
wire   [7:0] grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_v1_buffer_V_address0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_v1_buffer_V_ce0;
wire   [63:0] grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TDATA;
wire    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TVALID;
wire    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_input1_TREADY;
wire   [7:0] grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_address0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_ce0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_we0;
wire   [63:0] grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_d0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TREADY;
wire   [31:0] grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TDATA;
wire    grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TVALID;
wire    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TREADY;
wire   [7:0] grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_v1_buffer_V_address0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_v1_buffer_V_ce0;
wire   [63:0] grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TDATA;
wire    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TVALID;
reg    grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start_reg;
reg    ap_block_state13_ignore_call1;
wire    ap_CS_fsm_state16;
reg    grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg   [31:0] i_2_fu_66;
wire   [31:0] i_4_fu_179_p2;
reg    ap_block_state13;
reg    ap_block_state11;
reg    ap_block_state11_io;
reg    ap_block_state1;
wire   [0:0] tmp_fu_190_p1;
wire    ap_CS_fsm_state20;
wire    regslice_both_output1_U_apdone_blk;
wire    regslice_both_output2_U_apdone_blk;
wire    regslice_both_output3_U_apdone_blk;
wire    regslice_both_output4_U_apdone_blk;
reg    ap_block_state20;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_block_state12;
reg    ap_block_state12_io;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    regslice_both_input1_U_apdone_blk;
wire   [63:0] input1_TDATA_int_regslice;
wire    input1_TVALID_int_regslice;
reg    input1_TREADY_int_regslice;
wire    regslice_both_input1_U_ack_in;
wire    regslice_both_input2_U_apdone_blk;
wire   [511:0] input2_TDATA_int_regslice;
wire    input2_TVALID_int_regslice;
reg    input2_TREADY_int_regslice;
wire    regslice_both_input2_U_ack_in;
wire    regslice_both_input3_U_apdone_blk;
wire   [7:0] input3_TDATA_int_regslice;
wire    input3_TVALID_int_regslice;
reg    input3_TREADY_int_regslice;
wire    regslice_both_input3_U_ack_in;
reg   [63:0] output1_TDATA_int_regslice;
reg    output1_TVALID_int_regslice;
wire    output1_TREADY_int_regslice;
wire    regslice_both_output1_U_vld_out;
wire    output2_TREADY_int_regslice;
wire    regslice_both_output2_U_vld_out;
reg    output3_TVALID_int_regslice;
wire    output3_TREADY_int_regslice;
wire    regslice_both_output3_U_vld_out;
reg    output4_TVALID_int_regslice;
wire    output4_TREADY_int_regslice;
wire    regslice_both_output4_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start_reg = 1'b0;
#0 grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start_reg = 1'b0;
#0 grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start_reg = 1'b0;
#0 grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start_reg = 1'b0;
#0 grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start_reg = 1'b0;
end

config_parser_v1_buffer_V_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
v1_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(v1_buffer_V_address0),
    .ce0(v1_buffer_V_ce0),
    .we0(v1_buffer_V_we0),
    .d0(v1_buffer_V_d0),
    .q0(v1_buffer_V_q0)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_35_1 grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_ready),
    .input1_TVALID(input1_TVALID_int_regslice),
    .config_num(config_num_reg_194),
    .input1_TDATA(input1_TDATA_int_regslice),
    .input1_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_input1_TREADY),
    .v1_buffer_V_address0(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_address0),
    .v1_buffer_V_ce0(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_ce0),
    .v1_buffer_V_we0(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_we0),
    .v1_buffer_V_d0(grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_d0)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_41_2 grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_ready),
    .output1_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TREADY),
    .config_num(config_num_reg_194),
    .v1_buffer_V_address0(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_v1_buffer_V_address0),
    .v1_buffer_V_ce0(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_v1_buffer_V_ce0),
    .v1_buffer_V_q0(v1_buffer_V_q0),
    .output1_TDATA(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TDATA),
    .output1_TVALID(grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TVALID)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_61_5 grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_ready),
    .input1_TVALID(input1_TVALID_int_regslice),
    .num_ops(num_ops_reg_206),
    .input1_TDATA(input1_TDATA_int_regslice),
    .input1_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_input1_TREADY),
    .v1_buffer_V_address0(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_address0),
    .v1_buffer_V_ce0(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_ce0),
    .v1_buffer_V_we0(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_we0),
    .v1_buffer_V_d0(grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_d0)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_54_4 grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_ready),
    .output2_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TREADY),
    .tmp_6(tmp_1_reg_236),
    .output2_TDATA(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TDATA),
    .output2_TVALID(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TVALID)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_70_6 grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_ready),
    .output1_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TREADY),
    .num_ops(num_ops_reg_206),
    .v1_buffer_V_address0(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_v1_buffer_V_address0),
    .v1_buffer_V_ce0(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_v1_buffer_V_ce0),
    .v1_buffer_V_q0(v1_buffer_V_q0),
    .output1_TDATA(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TDATA),
    .output1_TVALID(grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TVALID)
);

config_parser_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input1_TDATA),
    .vld_in(input1_TVALID),
    .ack_in(regslice_both_input1_U_ack_in),
    .data_out(input1_TDATA_int_regslice),
    .vld_out(input1_TVALID_int_regslice),
    .ack_out(input1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input1_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 512 ))
regslice_both_input2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input2_TDATA),
    .vld_in(input2_TVALID),
    .ack_in(regslice_both_input2_U_ack_in),
    .data_out(input2_TDATA_int_regslice),
    .vld_out(input2_TVALID_int_regslice),
    .ack_out(input2_TREADY_int_regslice),
    .apdone_blk(regslice_both_input2_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input3_TDATA),
    .vld_in(input3_TVALID),
    .ack_in(regslice_both_input3_U_ack_in),
    .data_out(input3_TDATA_int_regslice),
    .vld_out(input3_TVALID_int_regslice),
    .ack_out(input3_TREADY_int_regslice),
    .apdone_blk(regslice_both_input3_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output1_TDATA_int_regslice),
    .vld_in(output1_TVALID_int_regslice),
    .ack_in(output1_TREADY_int_regslice),
    .data_out(output1_TDATA),
    .vld_out(regslice_both_output1_U_vld_out),
    .ack_out(output1_TREADY),
    .apdone_blk(regslice_both_output1_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TDATA),
    .vld_in(grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TVALID),
    .ack_in(output2_TREADY_int_regslice),
    .data_out(output2_TDATA),
    .vld_out(regslice_both_output2_U_vld_out),
    .ack_out(output2_TREADY),
    .apdone_blk(regslice_both_output2_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output3_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_size_reg_212),
    .vld_in(output3_TVALID_int_regslice),
    .ack_in(output3_TREADY_int_regslice),
    .data_out(output3_TDATA),
    .vld_out(regslice_both_output3_U_vld_out),
    .ack_out(output3_TREADY),
    .apdone_blk(regslice_both_output3_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output4_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(trunc_ln232_reg_217),
    .vld_in(output4_TVALID_int_regslice),
    .ack_in(output4_TREADY_int_regslice),
    .data_out(output4_TDATA),
    .vld_out(regslice_both_output4_U_vld_out),
    .ack_out(output4_TREADY),
    .apdone_blk(regslice_both_output4_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
            grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state11_io)) & (1'b1 == ap_CS_fsm_state11))) begin
        i_2_fu_66 <= 32'd0;
    end else if ((~((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        i_2_fu_66 <= i_4_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_num_reg_194 <= config_num_fu_141_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        data_num_reg_201 <= data_num_fu_145_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        num_ops_reg_206 <= num_ops_fu_149_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        output_size_reg_212 <= output_size_fu_153_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        tmp_1_reg_236 <= input2_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln232_reg_217 <= trunc_ln232_fu_157_p1;
    end
end

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state11_io))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if (((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state12_io))) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input3_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if (((input1_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input1_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input1_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input1_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input1_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state20))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state20))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        input1_TDATA_blk_n = input1_TVALID_int_regslice;
    end else begin
        input1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | (~((input1_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        input1_TREADY_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        input1_TREADY_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_input1_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        input1_TREADY_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_input1_TREADY;
    end else begin
        input1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        input2_TDATA_blk_n = input2_TVALID_int_regslice;
    end else begin
        input2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        input2_TREADY_int_regslice = 1'b1;
    end else begin
        input2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        input3_TDATA_blk_n = input3_TVALID_int_regslice;
    end else begin
        input3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((input3_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        input3_TREADY_int_regslice = 1'b1;
    end else begin
        input3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        output1_TDATA_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TDATA;
    end else if (((1'b1 == ap_CS_fsm_state10) & (grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TVALID == 1'b1))) begin
        output1_TDATA_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TDATA;
    end else begin
        output1_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        output1_TVALID_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output1_TVALID_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TVALID;
    end else begin
        output1_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        output3_TDATA_blk_n = output3_TREADY_int_regslice;
    end else begin
        output3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state11_io)) & (1'b1 == ap_CS_fsm_state11))) begin
        output3_TVALID_int_regslice = 1'b1;
    end else begin
        output3_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        output4_TDATA_blk_n = output4_TREADY_int_regslice;
    end else begin
        output4_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state11_io)) & (1'b1 == ap_CS_fsm_state11))) begin
        output4_TVALID_int_regslice = 1'b1;
    end else begin
        output4_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        v1_buffer_V_address0 = grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_v1_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        v1_buffer_V_address0 = grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        v1_buffer_V_address0 = grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_v1_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        v1_buffer_V_address0 = grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_address0;
    end else begin
        v1_buffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        v1_buffer_V_ce0 = grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_v1_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        v1_buffer_V_ce0 = grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        v1_buffer_V_ce0 = grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_v1_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        v1_buffer_V_ce0 = grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_ce0;
    end else begin
        v1_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        v1_buffer_V_d0 = grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        v1_buffer_V_d0 = grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_d0;
    end else begin
        v1_buffer_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        v1_buffer_V_we0 = grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_v1_buffer_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        v1_buffer_V_we0 = grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_v1_buffer_V_we0;
    end else begin
        v1_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((input1_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln35_fu_161_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((input1_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln35_fu_161_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state11_io)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if ((~((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0) | (1'b1 == ap_block_state12_io)) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if ((~((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if ((~((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0)) & (icmp_ln51_fu_174_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((input3_TVALID_int_regslice == 1'b1) & (tmp_fu_190_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if (((input3_TVALID_int_regslice == 1'b1) & (tmp_fu_190_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if ((~((regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((input1_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state11 = ((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state11_io = ((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state12 = ((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state12_io = ((output4_TREADY_int_regslice == 1'b0) | (output3_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state13 = ((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state13_ignore_call1 = ((icmp_ln51_fu_174_p2 == 1'd0) & (input2_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state20 = ((regslice_both_output4_U_apdone_blk == 1'b1) | (regslice_both_output3_U_apdone_blk == 1'b1) | (regslice_both_output2_U_apdone_blk == 1'b1) | (regslice_both_output1_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign config_num_fu_141_p1 = input1_TDATA_int_regslice[31:0];

assign data_num_fu_145_p1 = input1_TDATA_int_regslice[31:0];

assign grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_35_1_fu_102_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_41_2_fu_110_output1_TREADY = (output1_TREADY_int_regslice & ap_CS_fsm_state10);

assign grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_54_4_fu_126_output2_TREADY = (output2_TREADY_int_regslice & ap_CS_fsm_state15);

assign grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_61_5_fu_118_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_70_6_fu_133_output1_TREADY = (output1_TREADY_int_regslice & ap_CS_fsm_state19);

assign i_4_fu_179_p2 = (i_2_fu_66 + 32'd1);

assign icmp_ln35_fu_161_p2 = ((config_num_reg_194 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_174_p2 = ((i_2_fu_66 == data_num_reg_201) ? 1'b1 : 1'b0);

assign input1_TREADY = regslice_both_input1_U_ack_in;

assign input2_TREADY = regslice_both_input2_U_ack_in;

assign input3_TREADY = regslice_both_input3_U_ack_in;

assign num_ops_fu_149_p1 = input1_TDATA_int_regslice[31:0];

assign output1_TVALID = regslice_both_output1_U_vld_out;

assign output2_TVALID = regslice_both_output2_U_vld_out;

assign output3_TVALID = regslice_both_output3_U_vld_out;

assign output4_TVALID = regslice_both_output4_U_vld_out;

assign output_size_fu_153_p1 = input1_TDATA_int_regslice[31:0];

assign tmp_fu_190_p1 = input3_TDATA_int_regslice[0:0];

assign trunc_ln232_fu_157_p1 = input1_TDATA_int_regslice[15:0];

endmodule //config_parser
